name: Build IaC

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  allFiles: ${{ github.event_name != 'pull_request' || ( github.base_ref == 'main') }}

permissions:
  id-token: write
  contents: read
  security-events: write

jobs:
  build:
    environment: demo
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ID_CLIENT_ID }}
          tenant-id: ${{ secrets.ID_TENANT_ID }}
          subscription-id: ${{ secrets.ID_SUBSCRIPTION_ID }}
      - name: Setup Bicep
        uses: anthony-c-martin/setup-bicep@v0.1
      - name: Test Bicep
        run: |
          bicep --version
          bicep test 'test/test.run.bicep'
      - uses: maikvandergaag/action-biceplint@main
        with:
          allfiles: ${{ env.allFiles }}
          create-sarif: true
          markdown-report: false
          sarif-output-path: bicep-lint.sarif
      - name: Upload SARIF file
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: bicep-lint.sarif
          category: bicep-linting
      - uses: actions/upload-artifact@v4
        name: Upload IaC artifacts
        with:
          name: iac
          path: |
            ${{ github.workspace }}/**/*.bicep
            ${{ github.workspace }}/**/*.bicepparam