name: Software Development Platform

on:
  workflow_run:
    workflows: ["Build Infra Structure as Code"]
    types: [completed]
    branches:
      - 'main'
  workflow_dispatch:

env:
  bicepfiles: '("main.bicep")'
  bicepparameterfiles: '("main-param.bicepparam" "main-param-prd.bicepparam")'
  bicepfolder: 'bicep/sdp/'
  artifactName: 'bicep-artifacts'
  deploymentFile: 'main.json'
  parameterFile: 'main-param.json'
  parameterFilePrd: 'main-param-prd.json'
  resourcegroupname: ${{ secrets.AZURE_SDP_RESOURCEGROUP }}

jobs:
  deploy:
    environment: demo
    name: Deploy SDP TST
    if: github.event_name != 'pull_request'
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Download coverage artifacts
        uses: actions/download-artifact@v4
        with:
          run-id: ${{ github.event.workflow_run.id }}