name: Deploy to Azure
run-name: Deploy to Azure - ${{ github.event_name == 'workflow_run' && github.event.workflow_run.head_branch || inputs.workflow_run_id }}

on:
  workflow_run:
    workflows: ["Build Infra Structure as Code"]
    types: [completed]
    branches:
      - 'main'
  workflow_dispatch:
    inputs:
      workflow_run_id:
        description: 'Workflow run ID'
        required: true
        type: string

jobs:
  deploy:
    environment: demo
    name: Deploy to Azure
    permissions:
      contents: read
      id-token: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - name: Download coverage artifacts
        uses: actions/download-artifact@v4
        with:
          run-id: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.id || inputs.workflow_run_id }}
          github-token: ${{ github.token}}
          name: iac