name: Software Development Platform

on:
  workflow_run:
    workflows: ["Build Infra Structure as Code"]
    types: [completed]
    branches:
      - 'main'
  workflow_dispatch:
    inputs:
      workflow_run_id:
        description: 'Workflow run ID'
        required: true
        default: '0'
        type: string

jobs:
  deploy:
    environment: demo
    name: Deploy SDP TST
    if: github.event_name != 'pull_request'
    permissions:
      contents: read
      id-token: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - run: echo "event name is:" ${{ github.event_name }} 
      - run: echo "event type is:" ${{ github.event.action }} 
      - name: Download coverage artifacts
        uses: actions/download-artifact@v4
        with:
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ github.token}}
          name: iac